variables:
  TF_WORKSPACE_NAME: "Prod-BI"

image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - terraform init
  - terraform workspace new $TF_WORKSPACE_NAME || terraform workspace select $TF_WORKSPACE_NAME

stages:
    - validate
    - plan
    - apply

validate:
  stage: validate
  script:
    - terraform validate
  only:
    - production

plan:
  stage: plan
  script:
    - terraform init
    - terraform plan 
  only:
    - production


apply:
  stage: apply
  script:
    - terraform apply -auto-approve 
  only:
    - production
  dependencies:
    - plan
  when: manual
