image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - terraform init
  - terraform fmt

stages:
    - validate
    - plan
    - apply

validate:
  stage: validate
  script:
    - terraform validate
  only:
    - main

plan:
  stage: plan
  script:
    - terraform plan 
  only:
    - main

apply:
  stage: apply
  script:
    - terraform apply -auto-approve 
  only:
    - main
  dependencies:
    - plan
