#Created by "YLT"

module "vpc" {
  source = "../VPC"
}


#Creating Client VPN Endpoint
resource "aws_ec2_client_vpn_endpoint" "client-vpn-for-bi" {
  vpc_id                 = "vpc-id"
  security_group_ids     = [module.vpc.clientvpn-sg-id]
  description            = "Client VPN Endpoint for Prod BI"
  client_cidr_block      = "10.10.0.0/22"
  server_certificate_arn = "arn of certificate" #that is generated by ACM
  authentication_options {
    type                       = "certificate-authentication"
    root_certificate_chain_arn = "arn of certificate" #that is generated by ACM
  }
  connection_log_options {
    enabled = false # Set to true if you want connection logs
  }
  split_tunnel       = true
  tags   = {
    Name = lookup(var.name_clientvpn, terraform.workspace)
  }
}

#Association with subnets
resource "aws_ec2_client_vpn_network_association" "subnet-association" {
  client_vpn_endpoint_id = aws_ec2_client_vpn_endpoint.client-vpn-for-bi.id
  subnet_id              = "subnet_id"
}


#Adding Client VPN Ingress Authorization Rule
resource "aws_ec2_client_vpn_authorization_rule" "clienvpn-authorization-rule" {
  client_vpn_endpoint_id = aws_ec2_client_vpn_endpoint.client-vpn-for-bi.id
  target_network_cidr    = "172.31.32.0/20"
  authorize_all_groups   = true
}

